alias free="free -h" # Manjaro has free command built-in
alias logs="journalctl -f" # Use journalctl instead of system.log
alias pkill="pkill -f"
alias reload="source ~/.zshrc"
alias shutdown="shutdown -h now"
alias top="top -o %CPU"
alias update="sudo pacman -Syu" # Update using pacman
alias pacman-clean="sudo pacman -Qdtq" # Clean unused packages
alias yay-update="yay -Syu" # Update using yay
alias yay-clean="yay -Qdtq" # Clean unused packages
